groups:
- name: 服务器资源监控
  rules:
  - alert: 内存使用率过高
    expr: 100 - (node_memory_MemAvailable_bytes{job=~"(Secs_DMZ_Node)"} / node_memory_MemTotal_bytes{job=~"(Secs_DMZ_Node)"}) * 100 > 90
    for: 3m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{ $labels.instance }} 内存使用率过高, 请尽快处理！"
      description: "{{ $labels.instance }}内存使用率超过90%, 当前使用率: {{ $value }}%"

  - alert: 服务器宕机
    expr: up{job=~"(Secs_DMZ_Node)"} == 0
    for: 15s
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.instance}} 服务器宕机, 请尽快处理!"
      description: "{{$labels.instance}} 服务器延时超过1分钟, 当前状态: {{ $value }}"

  - alert: CPU高负荷
    expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle",job=~"(Secs_DMZ_Node)"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.instance}} CPU使用率过高, 请尽快处理！"
      description: "{{$labels.instance}} CPU使用大于90%, 当前使用率: {{ $value }}%"

  - alert: 磁盘IO性能
    expr: avg(irate(node_disk_io_time_seconds_total{job=~"(Secs_DMZ_Node)"}[5m])) by(instance) * 100 > 90
    for: 5m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.instance}} 流入磁盘IO使用率过高, 请尽快处理！"
      description: "{{$labels.instance}} 流入磁盘IO大于90%, 当前使用率: {{ $value }}%"

  - alert: 网络流入
    expr: ((sum(rate (node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',job=~"(Secs_DMZ_Node)"}[5m])) by (instance)) / 1024 / 1024 * 8) > 100
    for: 5m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.instance}} 流入网络带宽过高, 请尽快处理！"
      description: "{{$labels.instance}} 流入网络带宽持续5分钟高于100M, RX当前带宽使用率: {{$value}}Mbps"

  - alert: 网络流出
    expr: ((sum(rate (node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',job=~"(Secs_DMZ_Node)"}[5m])) by (instance)) / 1024 / 1024 * 8) > 100
    for: 5m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.instance}} 流出网络带宽过高, 请尽快处理！"
      description: "{{$labels.instance}} 流出网络带宽持续5分钟高于100M, RX当前带宽使用率: {$value}}Mbps"

  - alert: TCP连接数
    expr: node_netstat_Tcp_CurrEstab{job=~"(Secs_DMZ_Node)"} > 10000
    for: 2m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: " TCP_ESTABLISHED 当前会话连接数过高！"
      description: "{{$labels.instance}} 当前连接数 {{ $value }}%"

  - alert: 磁盘容量
    expr: 100 - (node_filesystem_free_bytes{fstype=~"ext.?|xfs|btrfs",job=~"(Secs_DMZ_Node)"}/node_filesystem_size_bytes{fstype=~"ext.?|xfs|btrfs",job=~"(Secs_DMZ_Node)"} * 100) > 90
    for: 1m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{$labels.mountpoint}} 磁盘分区使用率过高, 请尽快处理！"
      description: "{{$labels.instance}} 磁盘分区使用大于90%, 当前使用率: {{ $value }}%."
