groups:
- name: 网络设备ping检测
  rules:
  - alert: 网络设备不可达
    expr: probe_success{job=~"DMZ_icmp_ping"} == 0
    for: 15s
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "{{ $labels.instance }}  无法ping通"
      description: "网络地址 {{$labels.instance}} 超过1分钟 ping不通, 当前状态: {{ $value }}"
