groups:
- name: SSL证书检测
  rules:
  - alert: "SSL证书过期警告"
    expr: (probe_ssl_earliest_cert_expiry{job="http_check"} - time())/86400 < 30
    for: 2m
    labels:
      severity: 严重告警
      team: ops
    annotations:
      summary: "ssl证书过期警告"
      description: '域名 {{$labels.instance}} 的证书还有{{ printf "%.1f" $value }} 天就过期了,请尽快更新证书'
